# Generated by Django 3.0.8 on 2020-09-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
